In [15]:
import os

directory = '/home/cyrus/Downloads/images_gz2/images'
file_list = []

for filename in os.listdir(directory):
    file_path = os.path.join(directory, filename)
    
    if os.path.isfile(file_path):
        file_list.append(filename)

# print(file_list)

In [3]:
import pandas as pd
import numpy as np

In [4]:
galaxy_df = pd.read_csv('/home/cyrus/Documents/galaxy_df_cleaned.csv')
filename_mapping = pd.read_csv('/home/cyrus/Downloads/gz2_filename_mapping.csv')

In [5]:
galaxy_df = galaxy_df.drop('Unnamed: 0', axis = 1)
galaxy_df

,specobjid,dr8objid,dr7objid,ra,dec,rastring,decstring,sample,gz2class,total_classifications,...,t11_arms_number_a36_more_than_4_fraction,t11_arms_number_a36_more_than_4_weighted_fraction,t11_arms_number_a36_more_than_4_debiased,t11_arms_number_a36_more_than_4_flag,t11_arms_number_a37_cant_tell_count,t11_arms_number_a37_cant_tell_weight,t11_arms_number_a37_cant_tell_fraction,t11_arms_number_a37_cant_tell_weighted_fraction,t11_arms_number_a37_cant_tell_debiased,t11_arms_number_a37_cant_tell_flag
0,1.802675e+18,NaN,588017703996096547,160.990400,11.703790,10:43:57.70,+11:42:13.6,original,Uncertain,44,...,0.225,0.225,0.225,0,10,10.0,0.250,0.250,0.250,0
1,1.992984e+18,NaN,587738569780428805,192.410830,15.164207,12:49:38.60,+15:09:51.1,original,Spiral,45,...,0.000,0.000,0.000,0,0,0.0,0.000,0.000,0.000,0
2,1.489569e+18,NaN,587735695913320507,210.802200,54.348953,14:03:12.53,+54:20:56.2,original,Spiral,46,...,0.651,0.651,0.651,0,3,3.0,0.070,0.070,0.070,0
3,2.924084e+18,1.237668e+18,587742775634624545,185.303420,18.382704,12:21:12.82,+18:22:57.7,original,Spiral,45,...,0.071,0.071,0.071,0,6,6.0,0.429,0.429,0.429,0
4,1.387165e+18,1.237658e+18,587732769983889439,187.366790,8.749928,12:29:28.03,+08:44:59.7,extra,Spiral,49,...,0.000,0.000,0.000,0,1,1.0,1.000,1.000,1.000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243495,2.013145e+18,1.237664e+18,587737807967092857,145.174330,63.154312,09:40:41.84,+63:09:15.5,original,Spiral,35,...,0.031,0.031,0.031,0,0,0.0,0.000,0.000,0.000,0
243496,3.333027e+17,1.237649e+18,588848898847605001,199.857380,-1.037356,13:19:25.77,-01:02:14.5,original,Spiral,40,...,0.000,0.000,0.000,0,0,0.0,0.000,0.000,0.000,0
243497,1.959147e+18,1.237661e+18,587735348018872369,139.620040,10.317866,09:18:28.81,+10:19:04.3,original,Elliptical,49,...,0.000,0.000,0.000,0,0,0.0,0.000,0.000,0.000,0
243498,4.673293e+17,1.237660e+18,588015508218577115,52.470364,-0.750249,03:29:52.89,+00:45:00.9,stripe82,Elliptical,43,...,0.000,0.000,0.000,0,0,0.0,0.000,0.000,0.000,0
243499,-9.999000e+03,1.237657e+18,587731512619893016,51.014656,-0.002116,03:24:03.52,+00:00:07.6,stripe82,Spiral,42,...,0.000,0.000,0.000,0,1,1.0,1.000,1.000,1.000,0

In [6]:
filename_mapping

                      objid            sample  asset_id
0        587722981736120347          original         1
1        587722981736579107          original         2
2        587722981741363294          original         3
3        587722981741363323          original         4
4        587722981741559888          original         5
...                     ...               ...       ...
355985  8647475122541625731  stripe82_coadd_2    355986
355986  8647475122541625762  stripe82_coadd_2    355987
355987  8647475122541625774  stripe82_coadd_2    355988
355988  8647475122761762019  stripe82_coadd_2    355989
355989  8647475122761762804  stripe82_coadd_2    355990

[355990 rows x 3 columns]

In [7]:
galaxy_df = galaxy_df.merge(filename_mapping, left_on = 'dr7objid', right_on = 'objid', how = 'left')
galaxy_df.reset_index(drop = True)

,specobjid,dr8objid,dr7objid,ra,dec,rastring,decstring,sample_x,gz2class,total_classifications,...,t11_arms_number_a36_more_than_4_flag,t11_arms_number_a37_cant_tell_count,t11_arms_number_a37_cant_tell_weight,t11_arms_number_a37_cant_tell_fraction,t11_arms_number_a37_cant_tell_weighted_fraction,t11_arms_number_a37_cant_tell_debiased,t11_arms_number_a37_cant_tell_flag,objid,sample_y,asset_id
0,1.802675e+18,NaN,588017703996096547,160.990400,11.703790,10:43:57.70,+11:42:13.6,original,Uncertain,44,...,0,10,10.0,0.250,0.250,0.250,0,588017703996096547,original,217750
1,1.992984e+18,NaN,587738569780428805,192.410830,15.164207,12:49:38.60,+15:09:51.1,original,Spiral,45,...,0,0,0.0,0.000,0.000,0.000,0,587738569780428805,original,112436
2,1.489569e+18,NaN,587735695913320507,210.802200,54.348953,14:03:12.53,+54:20:56.2,original,Spiral,46,...,0,3,3.0,0.070,0.070,0.070,0,587735695913320507,original,86566
3,2.924084e+18,1.237668e+18,587742775634624545,185.303420,18.382704,12:21:12.82,+18:22:57.7,original,Spiral,45,...,0,6,6.0,0.429,0.429,0.429,0,587742775634624545,original,182364
4,1.387165e+18,1.237658e+18,587732769983889439,187.366790,8.749928,12:29:28.03,+08:44:59.7,extra,Spiral,49,...,0,1,1.0,1.000,1.000,1.000,0,587732769983889439,extra,252712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243495,2.013145e+18,1.237664e+18,587737807967092857,145.174330,63.154312,09:40:41.84,+63:09:15.5,original,Spiral,35,...,0,0,0.0,0.000,0.000,0.000,0,587737807967092857,original,105335
243496,3.333027e+17,1.237649e+18,588848898847605001,199.857380,-1.037356,13:19:25.77,-01:02:14.5,original,Spiral,40,...,0,0,0.0,0.000,0.000,0.000,0,588848898847605001,original,242095
243497,1.959147e+18,1.237661e+18,587735348018872369,139.620040,10.317866,09:18:28.81,+10:19:04.3,original,Elliptical,49,...,0,0,0.0,0.000,0.000,0.000,0,587735348018872369,original,80714
243498,4.673293e+17,1.237660e+18,588015508218577115,52.470364,-0.750249,03:29:52.89,+00:45:00.9,stripe82,Elliptical,43,...,0,0,0.0,0.000,0.000,0.000,0,588015508218577115,stripe82,290330
243499,-9.999000e+03,1.237657e+18,587731512619893016,51.014656,-0.002116,03:24:03.52,+00:00:07.6,stripe82,Spiral,42,...,0,1,1.0,1.000,1.000,1.000,0,587731512619893016,stripe82,283811

In [8]:
galaxy_df

,specobjid,dr8objid,dr7objid,ra,dec,rastring,decstring,sample_x,gz2class,total_classifications,...,t11_arms_number_a36_more_than_4_flag,t11_arms_number_a37_cant_tell_count,t11_arms_number_a37_cant_tell_weight,t11_arms_number_a37_cant_tell_fraction,t11_arms_number_a37_cant_tell_weighted_fraction,t11_arms_number_a37_cant_tell_debiased,t11_arms_number_a37_cant_tell_flag,objid,sample_y,asset_id
0,1.802675e+18,NaN,588017703996096547,160.990400,11.703790,10:43:57.70,+11:42:13.6,original,Uncertain,44,...,0,10,10.0,0.250,0.250,0.250,0,588017703996096547,original,217750
1,1.992984e+18,NaN,587738569780428805,192.410830,15.164207,12:49:38.60,+15:09:51.1,original,Spiral,45,...,0,0,0.0,0.000,0.000,0.000,0,587738569780428805,original,112436
2,1.489569e+18,NaN,587735695913320507,210.802200,54.348953,14:03:12.53,+54:20:56.2,original,Spiral,46,...,0,3,3.0,0.070,0.070,0.070,0,587735695913320507,original,86566
3,2.924084e+18,1.237668e+18,587742775634624545,185.303420,18.382704,12:21:12.82,+18:22:57.7,original,Spiral,45,...,0,6,6.0,0.429,0.429,0.429,0,587742775634624545,original,182364
4,1.387165e+18,1.237658e+18,587732769983889439,187.366790,8.749928,12:29:28.03,+08:44:59.7,extra,Spiral,49,...,0,1,1.0,1.000,1.000,1.000,0,587732769983889439,extra,252712
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243495,2.013145e+18,1.237664e+18,587737807967092857,145.174330,63.154312,09:40:41.84,+63:09:15.5,original,Spiral,35,...,0,0,0.0,0.000,0.000,0.000,0,587737807967092857,original,105335
243496,3.333027e+17,1.237649e+18,588848898847605001,199.857380,-1.037356,13:19:25.77,-01:02:14.5,original,Spiral,40,...,0,0,0.0,0.000,0.000,0.000,0,588848898847605001,original,242095
243497,1.959147e+18,1.237661e+18,587735348018872369,139.620040,10.317866,09:18:28.81,+10:19:04.3,original,Elliptical,49,...,0,0,0.0,0.000,0.000,0.000,0,587735348018872369,original,80714
243498,4.673293e+17,1.237660e+18,588015508218577115,52.470364,-0.750249,03:29:52.89,+00:45:00.9,stripe82,Elliptical,43,...,0,0,0.0,0.000,0.000,0.000,0,588015508218577115,stripe82,290330
243499,-9.999000e+03,1.237657e+18,587731512619893016,51.014656,-0.002116,03:24:03.52,+00:00:07.6,stripe82,Spiral,42,...,0,1,1.0,1.000,1.000,1.000,0,587731512619893016,stripe82,283811

In [10]:
order = ['specobjid', 'dr8objid', 'dr7objid', 'rastring', 'decstring', 'gz2class', 'asset_id', 'sample_x', 'sample_y']
galaxy_df = galaxy_df[order]
galaxy_df

,specobjid,dr8objid,dr7objid,rastring,decstring,gz2class,asset_id,sample_x,sample_y
0,1.802675e+18,NaN,588017703996096547,10:43:57.70,+11:42:13.6,Uncertain,217750,original,original
1,1.992984e+18,NaN,587738569780428805,12:49:38.60,+15:09:51.1,Spiral,112436,original,original
2,1.489569e+18,NaN,587735695913320507,14:03:12.53,+54:20:56.2,Spiral,86566,original,original
3,2.924084e+18,1.237668e+18,587742775634624545,12:21:12.82,+18:22:57.7,Spiral,182364,original,original
4,1.387165e+18,1.237658e+18,587732769983889439,12:29:28.03,+08:44:59.7,Spiral,252712,extra,extra
...,...,...,...,...,...,...,...,...,...
243495,2.013145e+18,1.237664e+18,587737807967092857,09:40:41.84,+63:09:15.5,Spiral,105335,original,original
243496,3.333027e+17,1.237649e+18,588848898847605001,13:19:25.77,-01:02:14.5,Spiral,242095,original,original
243497,1.959147e+18,1.237661e+18,587735348018872369,09:18:28.81,+10:19:04.3,Elliptical,80714,original,original
243498,4.673293e+17,1.237660e+18,588015508218577115,03:29:52.89,+00:45:00.9,Elliptical,290330,stripe82,stripe82
243499,-9.999000e+03,1.237657e+18,587731512619893016,03:24:03.52,+00:00:07.6,Spiral,283811,stripe82,stripe82

In [11]:
galaxy_df = galaxy_df.sort_values(by = 'asset_id')
galaxy_df

,specobjid,dr8objid,dr7objid,rastring,decstring,gz2class,asset_id,sample_x,sample_y
103036,3.231894e+17,1.237649e+18,587722981741363294,12:11:42.06,-01:05:32.5,Elliptical,3,original,original
48661,3.231899e+17,1.237649e+18,587722981741363323,12:11:52.83,-01:13:10.3,Spiral,4,original,original
236879,3.231690e+17,1.237649e+18,587722981741559888,12:13:45.14,-01:14:18.3,Elliptical,5,original,original
73327,3.231718e+17,1.237649e+18,587722981741625481,12:13:53.76,-01:13:53.1,Elliptical,6,original,original
149348,3.231679e+17,1.237649e+18,587722981741625484,12:13:54.67,-01:05:04.6,Elliptical,7,original,original
...,...,...,...,...,...,...,...,...,...
9240,1.398536e+18,1.237660e+18,588015510368681992,03:53:26.22,+00:50:30.5,Spiral,295294,stripe82,stripe82
29300,1.398535e+18,1.237660e+18,588015510368682105,03:53:32.90,+01:02:33.2,Elliptical,295295,stripe82,stripe82
96486,1.398533e+18,1.237660e+18,588015510368682132,03:53:42.68,+00:55:55.2,Elliptical,295296,stripe82,stripe82
60081,1.398457e+18,1.237660e+18,588015510636265643,03:46:04.30,+00:53:06.2,Uncertain,295304,stripe82,stripe82
109432,1.195861e+18,1.237660e+18,588015510636265731,03:46:03.01,+01:00:06.4,Elliptical,295305,stripe82,stripe82

In [19]:
galaxy_df.to_csv('/home/cyrus/Documents/galaxy_df_final.csv')